(() => {
  const qs=(s,r=document)=>r.querySelector(s);
  const qsa=(s,r=document)=>[...r.querySelectorAll(s)];
  const CONFIG=window.AGE_CONFIG||{};
  const consentKey='age_cookie_choice_v2';
  const getConsent=()=>{try{return localStorage.getItem(consentKey)}catch(_){return null}};
  const setConsent=v=>{try{localStorage.setItem(consentKey,v)}catch(_){};return v};

  const menuBtn=qs('.menu-btn'),navLinks=qs('.nav-links');
  if(menuBtn&&navLinks){menuBtn.setAttribute('aria-expanded','false');menuBtn.setAttribute('aria-controls','site-navigation');navLinks.id='site-navigation';menuBtn.addEventListener('click',()=>{const open=navLinks.classList.toggle('open');menuBtn.setAttribute('aria-expanded',String(open));});qsa('.nav-links a').forEach(a=>a.addEventListener('click',()=>{navLinks.classList.remove('open');menuBtn.setAttribute('aria-expanded','false');}));}
  if(!qs('.skip-link')){const skip=document.createElement('a');skip.className='skip-link';skip.href='#main-content';skip.textContent='Skip to main content';document.body.prepend(skip);}
  const main=qs('main');if(main&&!main.id)main.id='main-content';
  const reveals=qsa('.reveal');
  if('IntersectionObserver'in window&&!window.matchMedia('(prefers-reduced-motion: reduce)').matches){const reveal=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('show');reveal.unobserve(e.target)}}),{threshold:.08});reveals.forEach(el=>reveal.observe(el));}else reveals.forEach(el=>el.classList.add('show'));

  const footerBottom=qs('.footer-bottom');
  if(footerBottom&&!qs('.footer-policy-links',footerBottom)){const links=document.createElement('span');links.className='footer-policy-links';links.innerHTML='<a href="privacy.html">Privacy</a> · <a href="terms.html">Terms</a> · <a href="cookies.html">Cookies</a> · <a href="refund-policy.html">Booking & Refunds</a> · <a href="data-rights.html">Data Rights</a> · <a href="newsletter.html">Blog Email</a> · <a href="copyright.html">Media & Licenses</a> · <a href="third-party.html">Third-Party Audit</a> · <button type="button" class="privacy-settings">Privacy choices</button>';footerBottom.appendChild(links);qs('.privacy-settings',links).addEventListener('click',()=>showConsent(true));}

  function loadScript(src,id,attrs={}){if(id&&document.getElementById(id))return;const s=document.createElement('script');s.src=src;s.async=true;if(id)s.id=id;Object.entries(attrs).forEach(([k,v])=>s.setAttribute(k,v));document.head.appendChild(s);}
  function loadGA(){const id=CONFIG.GA_MEASUREMENT_ID||'';if(!/^G-[A-Z0-9]+$/i.test(id)||id==='G-REPLACE_ME')return;window.dataLayer=window.dataLayer||[];window.gtag=function(){dataLayer.push(arguments)};window.gtag('js',new Date());window.gtag('config',id,{anonymize_ip:true});loadScript('https://www.googletagmanager.com/gtag/js?id='+encodeURIComponent(id),'age-ga');}
  function loadInstagram(){const existing=document.getElementById('age-instagram-sdk');if(existing){try{if(window.instgrm&&window.instgrm.Embeds)window.instgrm.Embeds.process();}catch(_){}return;}const s=document.createElement('script');s.src='https://www.instagram.com/embed.js';s.async=true;s.id='age-instagram-sdk';s.onload=()=>{try{if(window.instgrm&&window.instgrm.Embeds)window.instgrm.Embeds.process();}catch(_){}};document.head.appendChild(s);}
  function loadAds(){const pub=CONFIG.ADSENSE_PUBLISHER_ID||'';if(!/^ca-pub-\d+$/.test(pub)||pub==='ca-pub-REPLACE_ME')return;const existing=document.querySelector('script[data-age-adsense]');if(!existing){const s=document.createElement('script');s.async=true;s.src='https://pagead2.googlesyndication.com/pagead/js/adsbygoogle.js?client='+encodeURIComponent(pub);s.crossOrigin='anonymous';s.dataset.ageAdsense='1';document.head.appendChild(s);}qsa('[data-ad-container]').forEach(c=>c.hidden=false);window.adsbygoogle=window.adsbygoogle||[];qsa('.age-ad').forEach(ad=>{if(!ad.dataset.pushed){try{window.adsbygoogle.push({});ad.dataset.pushed='1'}catch(_){}}});}
  function loadExternalImages(){qsa('[data-external-src]').forEach(img=>{if(!img.src||img.dataset.loaded!=='1'){img.src=img.dataset.externalSrc;img.dataset.loaded='1';}});}
  function enableOptional(){try{if(window.gtag)window.gtag('consent','update',{analytics_storage:'granted',ad_storage:'granted',ad_user_data:'granted',ad_personalization:'granted'});}catch(_){};loadGA();loadInstagram();loadAds();loadExternalImages();}
  function showConsent(force=false){let banner=qs('.cookie-banner');if(banner&&!force)return;if(banner)banner.remove();banner=document.createElement('aside');banner.className='cookie-banner show';banner.setAttribute('role','dialog');banner.setAttribute('aria-labelledby','cookie-title');banner.innerHTML='<div class="cookie-inner"><div class="cookie-copy"><strong id="cookie-title">Privacy choices</strong><p>AGE uses essential storage for this choice. Optional services include Google Analytics, Instagram embeds, advertising and external images. Choose optional services only if you are comfortable with those third-party requests.</p></div><div class="cookie-actions"><button type="button" class="cookie-essential">Essential only</button><button type="button" class="cookie-optional">Allow optional</button><a class="btn btn-secondary" href="cookies.html">Cookie policy</a></div></div>';document.body.appendChild(banner);const save=choice=>{setConsent(choice);banner.remove();if(choice==='optional')enableOptional();};qs('.cookie-essential',banner).addEventListener('click',()=>save('essential'));qs('.cookie-optional',banner).addEventListener('click',()=>save('optional'));qs('.cookie-essential',banner).focus();}
  const current=getConsent();if(current==='optional')enableOptional();else if(!current)showConsent();

  const timeline=qs('[data-timeline]');if(timeline){const filters=qsa('[data-timeline-filter]',timeline),items=qsa('[data-timeline-item]',timeline),progress=qs('[data-timeline-progress]',timeline);const apply=filter=>{let visible=0;items.forEach(item=>{const show=filter==='all'||item.dataset.group===filter;item.hidden=!show;if(show)visible++;});filters.forEach(btn=>btn.setAttribute('aria-pressed',String(btn.dataset.timelineFilter===filter)));if(progress)progress.style.width=`${Math.max(12.5,(visible/items.length)*100)}%`;};filters.forEach(btn=>btn.addEventListener('click',()=>apply(btn.dataset.timelineFilter)));apply('all');}

  const setupMailForm=(form,subject,builder,statusText)=>{if(!form)return;const status=qs('[data-form-status]',form);form.addEventListener('submit',event=>{event.preventDefault();if(!form.checkValidity()){form.reportValidity();return;}const data=new FormData(form),body=builder(data);if(status){status.textContent=statusText;status.setAttribute('role','status');}window.location.href=`mailto:info@asiagroupofevents.pk?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;});};
  setupMailForm(qs('#bookingForm'),'AGE Event Booking Enquiry',data=>['AGE EVENT ENQUIRY','',`Name: ${data.get('name')}`,`Email: ${data.get('email')}`,`Phone: ${data.get('phone')}`,`Event type: ${data.get('event')}`,`Event date: ${data.get('date')||'Not specified'}`,`Guests: ${data.get('guests')||'Not specified'}`,`Location: ${data.get('location')||'Not specified'}`,`Services: ${data.get('services')||'Not specified'}`,`Details: ${data.get('details')||'Not specified'}`,'','Consent: submitted through the AGE website.'].join('\n'),'Your email app is opening with the enquiry. Nothing is confirmed until AGE approves a quotation.');
  setupMailForm(qs('#deletionForm'),'AGE Data Rights Request',data=>['AGE DATA RIGHTS REQUEST','',`Email: ${data.get('email')}`,`Reference (optional): ${data.get('reference')||'None'}`,`Request: ${data.get('request')}`,`Details (optional): ${data.get('details')||'None'}`,'','Submitted through the AGE website.'].join('\n'),'Your email app is opening so you can send the request to AGE.');
  setupMailForm(qs('#newsletterForm'),'AGE Blog Email Preference',data=>['AGE BLOG EMAIL PREFERENCE','',`Email: ${data.get('email')}`,`Preference: ${data.get('preference')}`,'','I understand this static website uses email to process the request; it does not silently subscribe me.'].join('\n'),'Your email app is opening. AGE will process your subscription preference manually.');
})();
